server:
  port: 9090

spring:
  application:
    name: msvc-products
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: JeSnxYamQEHXIrlmakrKEUIipaGJzjZN
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: railway
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

eureka:
  instance:
    hostname: http://eureka.railway.app/eureka
  client:
    serviceUrl:
      defaultZone: http://eureka.railway.app/eureka